"use client"

import { useState } from "react"

const translations = {
  en: {
    tagline: "Complete Business Solution Platform",
    heroTitle: "Build Your Dream Business with AI-Powered Tools",
    heroSubtitle: "From business plans to logos, get everything you need to start and grow your business worldwide.",
    instantPlans: "AI Business Plans",
    instantPlansDesc: "Generate comprehensive business plans instantly",
    worldwideCosts: "Global Cost Calculator",
    worldwideCostsDesc: "Calculate costs for any country worldwide",
    designTools: "Design Tools",
    designToolsDesc: "Create logos and banners professionally",
    smartAnalysis: "Smart Analysis",
    smartAnalysisDesc: "Pros/cons analysis and business insights",

    planGenerator: "Plan Generator",
    costCalculator: "Cost Calculator",
    prosConsAnalysis: "Pros/Cons",
    nameGenerator: "Name Generator",
    logoDesign: "Logo Design",
    bannerDesign: "Banner Design",
    templates: "Templates",
    help: "Help",

    // Business Plan Generator
    aiBusinessPlanGenerator: "AI Business Plan Generator",
    aiGeneratorDesc: "Create comprehensive business plans with detailed cost analysis and pros/cons evaluation",
    businessName: "Business Name",
    businessType: "Business Type",
    location: "Location",
    initialBudget: "Initial Budget",
    targetMarket: "Target Market",
    experience: "Your Experience",
    businessNamePlaceholder: "Enter your business name",
    selectBusinessType: "Select business type",
    locationPlaceholder: "Enter your location",
    budgetPlaceholder: "Enter your budget (e.g., $50,000)",
    targetMarketPlaceholder: "Describe your target customers",
    experiencePlaceholder: "Your relevant experience",
    generating: "Generating...",
    generatePlan: "Generate Business Plan",
    generatedBusinessPlan: "Generated Business Plan",
    preview: "Preview",
    downloadPDF: "Download PDF",

    // Cost Calculator
    worldwideBusinessCostCalculator: "Worldwide Business Cost Calculator",
    worldwideCostCalculatorDesc: "Calculate detailed business costs for any country and city worldwide",
    country: "Country",
    city: "City",
    businessSize: "Business Size",
    selectCountry: "Select country",
    selectCity: "Select city",
    selectSize: "Select size",
    calculating: "Calculating...",
    calculateCosts: "Calculate Costs",
    currency: "Currency",
    locationInfo: "Location Information",

    // Business Types
    restaurant: "Restaurant",
    retail: "Retail Store",
    ecommerce: "E-commerce",
    technology: "Technology",
    healthcare: "Healthcare",
    education: "Education",
    manufacturing: "Manufacturing",
    service: "Service Business",
    consulting: "Consulting",
    agriculture: "Agriculture",
    fitness: "Fitness & Gym",
    beauty: "Beauty & Salon",
    automotive: "Automotive",
    realestate: "Real Estate",
    travel: "Travel & Tourism",

    // Sizes
    small: "Small",
    medium: "Medium",
    large: "Large",

    // Cost Categories
    oneTimeCosts: "One-Time Costs",
    monthlyCosts: "Monthly Costs",
    yearlyCosts: "Yearly Costs",
    firstYearTotal: "First Year Total",
    initialInvestment: "Initial investment required",
    recurringExpenses: "Monthly recurring expenses",
    annualOperating: "Annual operating costs",
    totalInvestmentNeeded: "Total investment needed",

    detailedCostBreakdown: "Detailed Cost Breakdown",
    costBreakdownDesc: "Complete breakdown of all business costs",
    costCategory: "Cost Category",
    type: "Type",
    amount: "Amount",
    oneTime: "One-time",
    monthly: "Monthly",

    setupCosts: "Setup & Registration",
    equipmentCosts: "Equipment & Furniture",
    inventoryCosts: "Initial Inventory",
    licenseCosts: "Licenses & Permits",
    rentCosts: "Rent & Utilities",
    salaryCosts: "Staff Salaries",
    staffCosts: "Staff Salaries",
    marketingCosts: "Marketing & Advertising",
    utilityCosts: "Utilities",
    insuranceCosts: "Insurance",
    otherCosts: "Other Expenses",

    // Business Plan Sections
    executiveSummary: "Executive Summary",
    marketAnalysis: "Market Analysis",
    productsServices: "Products & Services",
    marketingStrategy: "Marketing Strategy",
    operationalPlan: "Operational Plan",
    managementTeam: "Management Team",
    financialProjections: "Financial Projections",
    riskAnalysis: "Risk Analysis",
    costBreakdown: "Cost Breakdown",
    whyStartBusiness: "Why Start This Business",
    potentialChallenges: "Potential Challenges",
    estimatedCosts: "Estimated Costs",

    // Pros/Cons Analyzer
    prosConsAnalyzer: "Business Pros & Cons Analyzer",
    prosConsAnalyzerDesc: "Get detailed analysis of advantages and challenges for your business idea",
    selectLocation: "Select location",
    analyzing: "Analyzing...",
    analyzeBusinessIdea: "Analyze Business Idea",
    businessViabilityScore: "Business Viability Score",
    overallScore: "Overall Score",
    difficulty: "Difficulty",
    timeToProfit: "Time to Profit",
    successRate: "Success Rate",
    recommendations: "Recommendations",
    highlyRecommended: "Highly Recommended",
    highlyRecommendedText: "This business shows excellent potential with strong market demand and good profit margins.",
    moderatelyRecommended: "Moderately Recommended",
    moderatelyRecommendedText: "This business has potential but requires careful planning and execution.",
    notRecommended: "Proceed with Caution",
    notRecommendedText:
      "This business faces significant challenges. Consider alternative options or extensive market research.",

    // Business Name Generator
    businessNameGenerator: "Business Name Generator",
    nameGeneratorDesc: "Generate creative and memorable business names with domain availability",
    keywords: "Keywords",
    keywordsPlaceholder: "Enter keywords (e.g., fast, fresh, tech)",
    keywordsHint: "Separate multiple keywords with commas",
    nameStyle: "Name Style",
    selectStyle: "Select style",
    generateNames: "Generate Names",
    generatedNames: "Generated Names",
    generatedNamesDesc: "Creative business name suggestions with domain availability",
    regenerate: "Regenerate",
    domain: "Domain",
    available: "Available",
    taken: "Taken",
    rating: "Rating",
    style: "Style",

    // Name Styles
    modern: "Modern",
    classic: "Classic",
    creative: "Creative",
    professional: "Professional",
    playful: "Playful",
    luxury: "Luxury",
    minimalist: "Minimalist",
    bold: "Bold",
    elegant: "Elegant",

    // Logo Designer
    logoDesigner: "AI Logo Designer",
    logoDesignerDesc: "Create professional logos for your business instantly",
    industry: "Industry",
    selectIndustry: "Select industry",
    logoStyle: "Logo Style",
    colorScheme: "Color Scheme",
    selectColor: "Select color",
    generateLogos: "Generate Logos",
    generatedLogos: "Generated Logos",
    generatedLogosDesc: "Professional logo designs for your business",
    download: "Download",

    // Colors
    blue: "Blue",
    green: "Green",
    purple: "Purple",
    red: "Red",
    orange: "Orange",
    teal: "Teal",
    pink: "Pink",
    gray: "Gray",

    // Banner Designer
    bannerDesigner: "Banner & Poster Designer",
    bannerDesignerDesc: "Create stunning banners and posters for marketing",
    tagline: "Tagline",
    taglinePlaceholder: "Enter your business tagline",
    bannerType: "Banner Type",
    selectBannerType: "Select banner type",
    bannerStyle: "Banner Style",
    generateBanners: "Generate Banners",
    generatedBanners: "Generated Banners",
    generatedBannersDesc: "Custom banners and posters for your marketing needs",
    socialMedia: "Social Media Post",
    websiteHeader: "Website Header",
    facebookCover: "Facebook Cover",
    linkedinBanner: "LinkedIn Banner",
    youtubeBanner: "YouTube Banner",
    instagramPost: "Instagram Post",

    // Templates
    businessTemplates: "Business Templates",
    templatesDesc: "Choose from our pre-built templates designed for different industries",
    difficulty: "Difficulty",
    easy: "Easy",
    hard: "Hard",
    investment: "Investment",
    timeToStart: "Time to Start",
    profitMargin: "Profit Margin",
    generatePlan: "Generate Plan",
    calculateCosts: "Calculate Costs",

    // Template Descriptions
    restaurantDesc: "Food service business with dine-in, takeout, or delivery options",
    retailDesc: "Physical or online store selling products to consumers",
    ecommerceDesc: "Online business selling products through digital platforms",
    technologyDesc: "Software, app development, or tech service business",
    healthcareDesc: "Medical services, clinics, or health-related businesses",
    educationDesc: "Schools, training centers, or educational services",
    manufacturingDesc: "Production and manufacturing of goods",
    serviceDesc: "Service-based business like cleaning, repair, or consulting",
    consultingDesc: "Professional advisory services in your area of expertise",
    agricultureDesc: "Farming, livestock, or agricultural product business",
    fitnessDesc: "Gyms, personal training, or wellness centers",
    beautyDesc: "Salons, spas, or cosmetic services",
    automotiveDesc: "Car repair, sales, or related services",
    realestateDesc: "Property sales, rentals, or development",
    travelDesc: "Travel agencies, tour operators, or related services",

    // Template Content
    executiveSummaryTemplate:
      "is a {businessType} business located in {location}, targeting {targetMarket}. With an initial investment of {budget}, we aim to provide high-quality products/services and achieve sustainable growth in the local market.",
    marketAnalysisTemplate:
      "The {businessType} industry in {location} shows strong growth potential. Our target market consists of local consumers who value quality and convenience. Market research indicates growing demand for our services.",
    productsServicesTemplate:
      "Our {businessType} will offer premium products/services designed to meet the specific needs of our target market. We focus on quality, customer satisfaction, and competitive pricing.",
    marketingStrategyTemplate:
      "We will reach {targetMarket} through digital marketing, local advertising, and word-of-mouth referrals. Our {businessType} will leverage social media and community engagement to build brand awareness.",
    operationalPlanTemplate:
      "Our {businessType} will operate from {location} with efficient processes and quality control measures. We will maintain high standards of service delivery and customer satisfaction.",
    managementTeamTemplate:
      "The management team brings {experience} to the business, ensuring professional operations and strategic decision-making for long-term success.",
    financialProjectionsTemplate:
      "With an initial investment of {budget}, our {businessType} projects steady revenue growth and profitability within the first year of operations.",
    riskAnalysisTemplate:
      "Key risks for our {businessType} include market competition, economic fluctuations, and operational challenges. We have developed mitigation strategies to address these potential issues.",

    // Pros for Business Types
    restaurantPros1: "High demand for food and dining experiences.",
    restaurantPros2: "Opportunity for creativity in menu and ambiance.",
    restaurantPros3: "Strong community engagement potential.",
    restaurantPros4: "Diverse revenue streams (dine-in, takeout, catering).",
    restaurantPros5: "Scalability through multiple locations or franchising.",

    retailPros1: "Direct customer interaction and feedback.",
    retailPros2: "Ability to showcase physical products.",
    retailPros3: "Building a local brand presence.",
    retailPros4: "Opportunity for personalized customer service.",
    retailPros5: "Adapting quickly to local market trends.",

    ecommercePros1: "Low overhead costs compared to physical stores.",
    ecommercePros2: "Global reach and 24/7 sales potential.",
    ecommercePros3: "Scalability with less physical infrastructure.",
    ecommercePros4: "Data-driven marketing and personalization.",
    ecommercePros5: "Flexibility in product offerings and inventory management.",

    technologyPros1: "High-profit margins for successful products/services.",
    technologyPros2: "Rapid innovation and growth potential.",
    technologyPros3: "Ability to impact a large user base.",
    technologyPros4: "Attracts highly skilled talent.",
    technologyPros5: "Potential for significant investment and acquisition.",

    healthcarePros1: "Ever-present demand for health services.",
    healthcarePros2: "High trust and reputation building potential.",
    healthcarePros3: "Positive societal impact.",
    healthcarePros4: "Stable revenue streams from recurring services.",
    healthcarePros5: "Opportunities for specialization and niche markets.",

    fitnessPros1: "Growing health and wellness trend.",
    fitnessPros2: "Community building and loyal customer base.",
    fitnessPros3: "Diverse service offerings (classes, personal training).",
    fitnessPros4: "Positive impact on clients' lives.",
    fitnessPros5: "Relatively low startup costs for certain models (e.g., online coaching).",

    // Cons for Business Types
    restaurantCons1: "High startup and operational costs.",
    restaurantCons2: "Intense competition and high failure rate.",
    restaurantCons3: "Long working hours and demanding schedule.",
    restaurantCons4: "Reliance on staff and food quality consistency.",
    restaurantCons5: "Regulatory compliance and health inspections.",

    retailCons1: "High overhead (rent, utilities, inventory).",
    retailCons2: "Competition from e-commerce and large chains.",
    retailCons3: "Inventory management challenges.",
    retailCons4: "Seasonal fluctuations in sales.",
    retailCons5: "Need for strong visual merchandising and customer experience.",

    ecommerceCons1: "Intense online competition.",
    ecommerceCons2: "High marketing costs to stand out.",
    ecommerceCons3: "Logistics and shipping complexities.",
    ecommerceCons4: "Customer trust and security concerns.",
    ecommerceCons5: "Returns and customer service management.",

    technologyCons1: "Rapid technological changes and obsolescence.",
    technologyCons2: "High R&D costs and need for continuous innovation.",
    technologyCons3: "Talent acquisition and retention challenges.",
    technologyCons4: "Intellectual property protection.",
    technologyCons5: "Market adoption and scaling difficulties.",

    healthcareCons1: "Strict regulations and compliance requirements.",
    healthcareCons2: "High capital investment for equipment and facilities.",
    healthcareCons3: "Complex billing and insurance processes.",
    healthcareCons4: "Staffing shortages and high labor costs.",
    healthcareCons5: "Risk of malpractice lawsuits.",

    fitnessCons1: "High competition from established gyms and online platforms.",
    fitnessCons2: "Client retention challenges.",
    fitnessCons3: "Need for certified trainers and quality equipment.",
    fitnessCons4: "Seasonal demand fluctuations.",
    fitnessCons5: "Injury liability and safety concerns.",

    // Help Center
    helpCenter: "Help Center",
    helpCenterDesc: "Find answers to your questions and get support for using GlobalBiz Pro.",

    // Auth & Subscription
    login: "Login",
    signup: "Sign Up",
    logout: "Logout",
    username: "Username",
    password: "Password",
    enterUsername: "Enter your username",
    enterPassword: "Enter your password",
    loginSuccess: "Logged in successfully!",
    signupSuccess: "Signed up successfully! Enjoy your free trial.",
    invalidCredentials: "Invalid username or password.",
    account: "Account",
    subscription: "Subscription",
    subscriptionManager: "Subscription Manager",
    subscriptionManagerDesc: "Manage your subscription and view trial status.",
    currentStatus: "Current Status",
    freeTrial: "Free Trial",
    subscribed: "Subscribed",
    trialDaysLeft: "Days Left",
    trialUsesLeft: "Uses Left",
    trialExpired: "Trial Expired",
    usesExhausted: "Uses Exhausted",
    subscribeNow: "Subscribe Now",
    choosePlan: "Choose Your Plan",
    monthlyPlan: "Monthly Plan",
    yearlyPlan: "Yearly Plan",
    monthlyPrice: "$9.99/month",
    yearlyPrice: "$99.99/year (Save 17%)",
    selectPlan: "Select Plan",
    paymentMethod: "Payment Method",
    selectPaymentMethod: "Select Payment Method",
    bkash: "Bkash",
    creditCard: "Credit Card",
    paypal: "PayPal",
    payNow: "Pay Now",
    paymentProcessing: "Processing Payment...",
    paymentSuccess: "Payment successful! Your subscription is now active.",
    paymentFailed: "Payment failed. Please try again.",
    premiumFeatureLocked: "This is a premium feature. Please subscribe or start your free trial to continue.",
    startFreeTrial: "Start Free Trial",
    trialLimitReached: "Your free trial limit has been reached. Please subscribe to continue using this feature.",
    trialTimeExpired: "Your free trial has expired. Please subscribe to continue using this feature.",

    // Website Builder
    websiteBuilder: "Website Builder",
    websiteBuilderDesc: "Design and generate professional websites for your business.",
    websiteName: "Website Name",
    websiteNamePlaceholder: "Enter your website name",
    websiteTemplate: "Website Template",
    selectTemplate: "Select template",
    templateModern: "Modern Business",
    templateCreative: "Creative Portfolio",
    templateEcommerce: "E-commerce Shop",
    templateMinimal: "Minimalist Blog",
    generateWebsite: "Generate Website",
    generatedWebsite: "Generated Website",
    websitePreview: "Website Preview",
    downloadWebsite: "Download Website (HTML/CSS)",
    websiteGenerating: "Generating Website...",
    websiteGeneratedSuccess: "Website generated successfully!",
    websiteGeneratedDesc: "Preview and download your custom-designed website.",
  },
  bn: {
    tagline: "সম্পূর্ণ ব্যবসায়িক সমাধান প্ল্যাটফর্ম",
    heroTitle: "AI-চালিত সরঞ্জাম দিয়ে আপনার স্বপ্নের ব্যবসা তৈরি করুন",
    heroSubtitle: "ব্যবসায়িক পরিকল্পনা থেকে লোগো পর্যন্ত, বিশ্বব্যাপী আপনার ব্যবসা শুরু এবং বৃদ্ধির জন্য আপনার প্রয়োজনীয় সবকিছু পান।",
    instantPlans: "AI ব্যবসায়িক পরিকল্পনা",
    instantPlansDesc: "তাৎক্ষণিক বিস্তৃত ব্যবসায়িক পরিকল্পনা তৈরি করুন",
    worldwideCosts: "বিশ্বব্যাপী খরচ ক্যালকুলেটর",
    worldwideCostsDesc: "বিশ্বের যেকোনো দেশের জন্য খরচ গণনা করুন",
    designTools: "ডিজাইন সরঞ্জাম",
    designToolsDesc: "পেশাদারভাবে লোগো এবং ব্যানার তৈরি করুন",
    smartAnalysis: "স্মার্ট বিশ্লেষণ",
    smartAnalysisDesc: "সুবিধা/অসুবিধা বিশ্লেষণ এবং ব্যবসায়িক অন্তর্দৃষ্টি",

    planGenerator: "পরিকল্পনা জেনারেটর",
    costCalculator: "খরচ ক্যালকুলেটর",
    prosConsAnalysis: "সুবিধা/অসুবিধা",
    nameGenerator: "নাম জেনারেটর",
    logoDesign: "লোগো ডিজাইন",
    bannerDesign: "ব্যানার ডিজাইন",
    templates: "টেমপ্লেট",
    help: "সাহায্য",

    // Business Plan Generator
    aiBusinessPlanGenerator: "AI ব্যবসায়িক পরিকল্পনা জেনারেটর",
    aiGeneratorDesc: "বিস্তারিত খরচ বিশ্লেষণ এবং সুবিধা/অসুবিধা মূল্যায়ন সহ বিস্তৃত ব্যবসায়িক পরিকল্পনা তৈরি করুন",
    businessName: "ব্যবসার নাম",
    businessType: "ব্যবসার ধরন",
    location: "অবস্থান",
    initialBudget: "প্রাথমিক বাজেট",
    targetMarket: "টার্গেট মার্কেট",
    experience: "আপনার অভিজ্ঞতা",
    businessNamePlaceholder: "আপনার ব্যবসার নাম লিখুন",
    selectBusinessType: "ব্যবসার ধরন নির্বাচন করুন",
    locationPlaceholder: "আপনার অবস্থান লিখুন",
    budgetPlaceholder: "আপনার বাজেট লিখুন (যেমন: $50,000)",
    targetMarketPlaceholder: "আপনার টার্গেট কাস্টমার বর্ণনা করুন",
    experiencePlaceholder: "আপনার প্রাসঙ্গিক অভিজ্ঞতা",
    generating: "তৈরি হচ্ছে...",
    generatePlan: "ব্যবসায়িক পরিকল্পনা তৈরি করুন",
    generatedBusinessPlan: "তৈরিকৃত ব্যবসায়িক পরিকল্পনা",
    preview: "পূর্বরূপ",
    downloadPDF: "PDF ডাউনলোড",

    // Cost Calculator
    worldwideBusinessCostCalculator: "বিশ্বব্যাপী ব্যবসায়িক খরচ ক্যালকুলেটর",
    worldwideCostCalculatorDesc: "বিশ্বের যেকোনো দেশ ও শহরের জন্য বিস্তারিত ব্যবসায়িক খরচ গণনা করুন",
    country: "দেশ",
    city: "শহর",
    businessSize: "ব্যবসার আকার",
    selectCountry: "দেশ নির্বাচন করুন",
    selectCity: "শহর নির্বাচন করুন",
    selectSize: "আকার নির্বাচন করুন",
    calculating: "গণনা করা হচ্ছে...",
    calculateCosts: "খরচ গণনা করুন",
    currency: "মুদ্রা",
    locationInfo: "অবস্থান তথ্য",

    // Business Types
    restaurant: "রেস্টুরেন্ট",
    retail: "খুচরা দোকান",
    ecommerce: "ই-কমার্স",
    technology: "প্রযুক্তি",
    healthcare: "স্বাস্থ্যসেবা",
    education: "শিক্ষা",
    manufacturing: "উৎপাদন",
    service: "সেবা ব্যবসা",
    consulting: "পরামর্শ",
    agriculture: "কৃষি",
    fitness: "ফিটনেস ও জিম",
    beauty: "বিউটি ও সেলুন",
    automotive: "মোটরগাড়ি",
    realestate: "রিয়েল এস্টেট",
    travel: "ভ্রমণ ও পর্যটন",

    // Sizes
    small: "ছোট",
    medium: "মাঝারি",
    large: "বড়",

    // Cost Categories
    oneTimeCosts: "একবারের খরচ",
    monthlyCosts: "মাসিক খরচ",
    yearlyCosts: "বার্ষিক খরচ",
    firstYearTotal: "প্রথম বছরের মোট",
    initialInvestment: "প্রাথমিক বিনিয়োগ প্রয়োজন",
    recurringExpenses: "মাসিক পুনরাবৃত্ত খরচ",
    annualOperating: "বার্ষিক পরিচালনা খরচ",
    totalInvestmentNeeded: "মোট বিনিয়োগ প্রয়োজন",

    detailedCostBreakdown: "বিস্তারিত খরচের ভাঙ্গন",
    costBreakdownDesc: "সমস্ত ব্যবসায়িক খরচের সম্পূর্ণ ভাঙ্গন",
    costCategory: "খরচের ক্যাটেগরি",
    type: "ধরন",
    amount: "পরিমাণ",
    oneTime: "একবার",
    monthly: "মাসিক",

    setupCosts: "সেটআপ ও নিবন্ধন",
    equipmentCosts: "যন্ত্রপাতি ও আসবাবপত্র",
    inventoryCosts: "প্রাথমিক মালামাল",
    licenseCosts: "লাইসেন্স ও অনুমতি",
    rentCosts: "ভাড়া ও ইউটিলিটি",
    salaryCosts: "কর্মচারী বেতন",
    staffCosts: "কর্মচারী বেতন",
    marketingCosts: "মার্কেটিং ও বিজ্ঞাপন",
    utilityCosts: "ইউটিলিটি",
    insuranceCosts: "বীমা",
    otherCosts: "অন্যান্য খরচ",

    // Business Plan Sections
    executiveSummary: "নির্বাহী সারসংক্ষেপ",
    marketAnalysis: "বাজার বিশ্লেষণ",
    productsServices: "পণ্য ও সেবা",
    marketingStrategy: "মার্কেটিং কৌশল",
    operationalPlan: "পরিচালনা পরিকল্পনা",
    managementTeam: "ব্যবস্থাপনা দল",
    financialProjections: "আর্থিক প্রক্ষেপণ",
    riskAnalysis: "ঝুঁকি বিশ্লেষণ",
    costBreakdown: "খরচের ভাঙ্গন",
    whyStartBusiness: "কেন এই ব্যবসা শুরু করবেন",
    potentialChallenges: "সম্ভাব্য চ্যালেঞ্জ",
    estimatedCosts: "আনুমানিক খরচ",

    // Pros/Cons Analyzer
    prosConsAnalyzer: "ব্যবসায়িক সুবিধা ও অসুবিধা বিশ্লেষক",
    prosConsAnalyzerDesc: "আপনার ব্যবসার ধারণার সুবিধা এবং চ্যালেঞ্জগুলির বিস্তারিত বিশ্লেষণ পান",
    selectLocation: "অবস্থান নির্বাচন করুন",
    analyzing: "বিশ্লেষণ করা হচ্ছে...",
    analyzeBusinessIdea: "ব্যবসায়িক ধারণা বিশ্লেষণ করুন",
    businessViabilityScore: "ব্যবসায়িক কার্যকারিতা স্কোর",
    overallScore: "সামগ্রিক স্কোর",
    difficulty: "কঠিনতা",
    timeToProfit: "লাভের সময়",
    successRate: "সাফল্যের হার",
    recommendations: "সুপারিশ",
    highlyRecommended: "অত্যন্ত প্রস্তাবিত",
    highlyRecommendedText: "এই ব্যবসাটি শক্তিশালী বাজার চাহিদা এবং ভাল লাভের মার্জিন সহ চমৎকার সম্ভাবনা দেখাচ্ছে।",
    moderatelyRecommended: "মাঝারিভাবে প্রস্তাবিত",
    moderatelyRecommendedText: "এই ব্যবসার সম্ভাবনা আছে তবে সতর্ক পরিকল্পনা এবং বাস্তবায়ন প্রয়োজন।",
    notRecommended: "সাবধানে এগিয়ে যান",
    notRecommendedText: "এই ব্যবসাটি উল্লেখযোগ্য চ্যালেঞ্জের সম্মুখীন। বিকল্প বিকল্প বা ব্যাপক বাজার গবেষণা বিবেচনা করুন।",

    // Business Name Generator
    businessNameGenerator: "ব্যবসায়িক নাম জেনারেটর",
    nameGeneratorDesc: "ডোমেইন উপলব্ধতা সহ সৃজনশীল এবং স্মরণীয় ব্যবসার নাম তৈরি করুন",
    keywords: "কীওয়ার্ড",
    keywordsPlaceholder: "কীওয়ার্ড লিখুন (যেমন: দ্রুত, তাজা, প্রযুক্তি)",
    keywordsHint: "একাধিক কীওয়ার্ড কমা দিয়ে আলাদা করুন",
    nameStyle: "নামের স্টাইল",
    selectStyle: "স্টাইল নির্বাচন করুন",
    generateNames: "নাম তৈরি করুন",
    generatedNames: "তৈরিকৃত নাম",
    generatedNamesDesc: "ডোমেইন উপলব্ধতা সহ সৃজনশীল ব্যবসার নামের পরামর্শ",
    regenerate: "পুনরায় তৈরি করুন",
    domain: "ডোমেইন",
    available: "উপলব্ধ",
    taken: "নেওয়া হয়েছে",
    rating: "রেটিং",
    style: "স্টাইল",

    // Name Styles
    modern: "আধুনিক",
    classic: "ক্লাসিক",
    creative: "সৃজনশীল",
    professional: "পেশাদার",
    playful: "খেলোয়াড়",
    luxury: "বিলাসবহুল",
    minimalist: "মিনিমালিস্ট",
    bold: "সাহসী",
    elegant: "মার্জিত",

    // Logo Designer
    logoDesigner: "AI লোগো ডিজাইনার",
    logoDesignerDesc: "তাৎক্ষণিক আপনার ব্যবসার জন্য পেশাদার লোগো তৈরি করুন",
    industry: "শিল্প",
    selectIndustry: "শিল্প নির্বাচন করুন",
    logoStyle: "লোগো স্টাইল",
    colorScheme: "রঙের স্কিম",
    selectColor: "রঙ নির্বাচন করুন",
    generateLogos: "লোগো তৈরি করুন",
    generatedLogos: "তৈরিকৃত লোগো",
    generatedLogosDesc: "আপনার ব্যবসার জন্য পেশাদার লোগো ডিজাইন",
    download: "ডাউনলোড",

    // Colors
    blue: "নীল",
    green: "সবুজ",
    purple: "বেগুনি",
    red: "লাল",
    orange: "কমলা",
    teal: "টিয়াল",
    pink: "গোলাপী",
    gray: "ধূসর",

    // Banner Designer
    bannerDesigner: "ব্যানার ও পোস্টার ডিজাইনার",
    bannerDesignerDesc: "মার্কেটিংয়ের জন্য অত্যাশ্চর্য ব্যানার এবং পোস্টার তৈরি করুন",
    tagline: "ট্যাগলাইন",
    taglinePlaceholder: "আপনার ব্যবসার ট্যাগলাইন লিখুন",
    bannerType: "ব্যানার ধরন",
    selectBannerType: "ব্যানার ধরন নির্বাচন করুন",
    bannerStyle: "ব্যানার স্টাইল",
    generateBanners: "ব্যানার তৈরি করুন",
    generatedBanners: "তৈরিকৃত ব্যানার",
    generatedBannersDesc: "আপনার মার্কেটিং প্রয়োজনের জন্য কাস্টম ব্যানার এবং পোস্টার",
    socialMedia: "সোশ্যাল মিডিয়া পোস্ট",
    websiteHeader: "ওয়েবসাইট হেডার",
    facebookCover: "ফেসবুক কভার",
    linkedinBanner: "লিঙ্কডইন ব্যানার",
    youtubeBanner: "ইউটিউব ব্যানার",
    instagramPost: "ইনস্টাগ্রাম পোস্ট",

    // Templates
    businessTemplates: "ব্যবসায়িক টেমপ্লেট",
    templatesDesc: "বিভিন্ন শিল্পের জন্য ডিজাইন করা আমাদের প্রি-বিল্ট টেমপ্লেট থেকে বেছে নিন",
    difficulty: "কঠিনতা",
    easy: "সহজ",
    hard: "কঠিন",
    investment: "বিনিয়োগ",
    timeToStart: "শুরু করার সময়",
    profitMargin: "লাভের মার্জিন",
    generatePlan: "পরিকল্পনা তৈরি করুন",
    calculateCosts: "খরচ গণনা করুন",

    // Template Descriptions
    restaurantDesc: "ডাইন-ইন, টেকআউট বা ডেলিভারি অপশন সহ খাদ্য সেবা ব্যবসা",
    retailDesc: "ভোক্তাদের কাছে পণ্য বিক্রয়কারী ফিজিক্যাল বা অনলাইন দোকান",
    ecommerceDesc: "ডিজিটাল প্ল্যাটফর্মের মাধ্যমে পণ্য বিক্রয়কারী অনলাইন ব্যবসা",
    technologyDesc: "সফটওয়্যার, অ্যাপ ডেভেলপমেন্ট বা টেক সার্ভিস ব্যবসা",
    healthcareDesc: "চিকিৎসা সেবা, ক্লিনিক বা স্বাস্থ্য-সম্পর্কিত ব্যবসা",
    educationDesc: "স্কুল, প্রশিক্ষণ কেন্দ্র বা শিক্ষামূলক সেবা",
    manufacturingDesc: "পণ্য উৎপাদন ও ম্যানুফ্যাকচারিং",
    serviceDesc: "পরিষ্কার, মেরামত বা পরামর্শের মতো সেবা-ভিত্তিক ব্যবসা",
    consultingDesc: "আপনার দক্ষতার ক্ষেত্রে পেশাদার পরামর্শ সেবা",
    agricultureDesc: "কৃষি, পশুপালন বা কৃষি পণ্য ব্যবসা",
    fitnessDesc: "জিম, ব্যক্তিগত প্রশিক্ষণ, বা সুস্থতা কেন্দ্র",
    beautyDesc: "সেলুন, স্পা, বা কসমেটিক পরিষেবা",
    automotiveDesc: "গাড়ি মেরামত, বিক্রয়, বা সম্পর্কিত পরিষেবা",
    realestateDesc: "সম্পত্তি বিক্রয়, ভাড়া, বা উন্নয়ন",
    travelDesc: "ভ্রমণ সংস্থা, ট্যুর অপারেটর, বা সম্পর্কিত পরিষেবা",

    // Template Content
    executiveSummaryTemplate:
      "{location} এ অবস্থিত একটি {businessType} ব্যবসা, যা {targetMarket} কে টার্গেট করে। {budget} প্রাথমিক বিনিয়োগের সাথে, আমরা উচ্চ মানের পণ্য/সেবা প্রদান এবং স্থানীয় বাজারে টেকসই বৃদ্ধি অর্জনের লক্ষ্য রাখি।",
    marketAnalysisTemplate:
      "{location} এ {businessType} শিল্প শক্তিশালী বৃদ্ধির সম্ভাবনা দেখায়। আমাদের টার্গেট মার্কেট স্থানীয় ভোক্তাদের নিয়ে গঠিত যারা গুণমান এবং সুবিধাকে মূল্য দেয়। বাজার গবেষণা আমাদের সেবার ক্রমবর্ধমান চাহিদা নির্দেশ করে।",
    productsServicesTemplate:
      "আমাদের {businessType} আমাদের টার্গেট মার্কেটের নির্দিষ্ট চাহিদা মেটানোর জন্য ডিজাইন করা প্রিমিয়াম পণ্য/সেবা অফার করবে। আমরা গুণমান, গ্রাহক সন্তুষ্টি এবং প্রতিযোগিতামূলক মূল্যের উপর ফোকাস করি।",
    marketingStrategyTemplate:
      "আমরা ডিজিটাল মার্কেটিং, স্থানীয় বিজ্ঞাপন এবং মুখে মুখে রেফারেলের মাধ্যমে {targetMarket} এর কাছে পৌঁছাব। আমাদের {businessType} ব্র্যান্ড সচেতনতা তৈরির জন্য সোশ্যাল মিডিয়া এবং কমিউনিটি এনগেজমেন্ট ব্যবহার করবে।",
    operationalPlanTemplate:
      "আমাদের {businessType} দক্ষ প্রক্রিয়া এবং গুণমান নিয়ন্ত্রণ ব্যবস্থা সহ {location} থেকে পরিচালিত হবে। আমরা সেবা প্রদান এবং গ্রাহক সন্তুষ্টির উচ্চ মান বজায় রাখব।",
    managementTeamTemplate:
      "ব্যবস্থাপনা দল ব্যবসায় {experience} নিয়ে আসে, দীর্ঘমেয়াদী সাফল্যের জন্য পেশাদার পরিচালনা এবং কৌশলগত সিদ্ধান্ত গ্রহণ নিশ্চিত করে।",
    financialProjectionsTemplate:
      "{budget} প্রাথমিক বিনিয়োগের সাথে, আমাদের {businessType} স্থির রাজস্ব বৃদ্ধি এবং পরিচালনার প্রথম বছরের মধ্যে লাভজনকতার প্রক্ষেপণ করে।",
    riskAnalysisTemplate:
      "আমাদের {businessType} এর মূল ঝুঁকিগুলির মধ্যে রয়েছে বাজার প্রতিযোগিতা, অর্থনৈতিক ওঠানামা এবং পরিচালনাগত চ্যালেঞ্জ। আমরা এই সম্ভাব্য সমস্যাগুলি মোকাবেলার জন্য প্রশমন কৌশল তৈরি করেছি।",

    // Pros for Business Types
    restaurantPros1: "খাদ্য এবং ডাইনিং অভিজ্ঞতার জন্য উচ্চ চাহিদা।",
    restaurantPros2: "মেনু এবং পরিবেশে সৃজনশীলতার সুযোগ।",
    restaurantPros3: "শক্তিশালী সম্প্রদায় জড়িত থাকার সম্ভাবনা।",
    restaurantPros4: "বিভিন্ন রাজস্ব প্রবাহ (ডাইন-ইন, টেকআউট, ক্যাটারিং)।",
    restaurantPros5: "একাধিক অবস্থান বা ফ্র্যাঞ্চাইজিংয়ের মাধ্যমে স্কেলেবিলিটি।",

    retailPros1: "সরাসরি গ্রাহক মিথস্ক্রিয়া এবং প্রতিক্রিয়া।",
    retailPros2: "শারীরিক পণ্য প্রদর্শনের ক্ষমতা।",
    retailPros3: "একটি স্থানীয় ব্র্যান্ড উপস্থিতি তৈরি করা।",
    retailPros4: "ব্যক্তিগতকৃত গ্রাহক সেবার সুযোগ।",
    retailPros5: "স্থানীয় বাজারের প্রবণতার সাথে দ্রুত মানিয়ে নেওয়া।",

    ecommercePros1: "শারীরিক দোকানের তুলনায় কম ওভারহেড খরচ।",
    ecommercePros2: "বিশ্বব্যাপী পৌঁছানো এবং 24/7 বিক্রয়ের সম্ভাবনা।",
    ecommercePros3: "কম শারীরিক অবকাঠামো সহ স্কেলেবিলিটি।",
    ecommercePros4: "ডেটা-চালিত বিপণন এবং ব্যক্তিগতকরণ।",
    ecommercePros5: "পণ্য অফার এবং ইনভেন্টরি ব্যবস্থাপনায় নমনীয়তা।",

    technologyPros1: "সফল পণ্য/সেবার জন্য উচ্চ লাভের মার্জিন।",
    technologyPros2: "দ্রুত উদ্ভাবন এবং বৃদ্ধির সম্ভাবনা।",
    technologyPros3: "একটি বৃহৎ ব্যবহারকারী বেসকে প্রভাবিত করার ক্ষমতা।",
    technologyPros4: "উচ্চ দক্ষ প্রতিভা আকর্ষণ করে।",
    technologyPros5: "উল্লেখযোগ্য বিনিয়োগ এবং অধিগ্রহণের সম্ভাবনা।",

    healthcarePros1: "স্বাস্থ্য সেবার জন্য সর্বদা চাহিদা বিদ্যমান।",
    healthcarePros2: "উচ্চ বিশ্বাস এবং খ্যাতি তৈরির সম্ভাবনা।",
    healthcarePros3: "ইতিবাচক সামাজিক প্রভাব।",
    healthcarePros4: "পুনরাবৃত্ত পরিষেবা থেকে স্থিতিশীল রাজস্ব প্রবাহ।",
    healthcarePros5: "বিশেষীকরণ এবং নির্দিষ্ট বাজারের জন্য সুযোগ।",

    fitnessPros1: "ক্রমবর্ধমান স্বাস্থ্য এবং সুস্থতার প্রবণতা।",
    fitnessPros2: "সম্প্রদায় তৈরি এবং অনুগত গ্রাহক বেস।",
    fitnessPros3: "বিভিন্ন পরিষেবা অফার (ক্লাস, ব্যক্তিগত প্রশিক্ষণ)।",
    fitnessPros4: "ক্লায়েন্টদের জীবনে ইতিবাচক প্রভাব।",
    fitnessPros5: "কিছু মডেলের জন্য তুলনামূলকভাবে কম স্টার্টআপ খরচ (যেমন, অনলাইন কোচিং)।",

    // Cons for Business Types
    restaurantCons1: "উচ্চ স্টার্টআপ এবং পরিচালনা খরচ।",
    restaurantCons2: "তীব্র প্রতিযোগিতা এবং উচ্চ ব্যর্থতার হার।",
    restaurantCons3: "দীর্ঘ কাজের সময় এবং চাহিদাপূর্ণ সময়সূচী।",
    restaurantCons4: "কর্মী এবং খাদ্যের গুণমানের ধারাবাহিকতার উপর নির্ভরতা।",
    restaurantCons5: "নিয়ন্ত্রক সম্মতি এবং স্বাস্থ্য পরিদর্শন।",

    retailCons1: "উচ্চ ওভারহেড (ভাড়া, ইউটিলিটি, ইনভেন্টরি)।",
    retailCons2: "ই-কমার্স এবং বড় চেইন থেকে প্রতিযোগিতা।",
    retailCons3: "ইনভেন্টরি ব্যবস্থাপনার চ্যালেঞ্জ।",
    retailCons4: "বিক্রয়ে মৌসুমী ওঠানামা।",
    retailCons5: "শক্তিশালী ভিজ্যুয়াল মার্চেন্ডাইজিং এবং গ্রাহক অভিজ্ঞতার প্রয়োজন।",

    ecommerceCons1: "তীব্র অনলাইন প্রতিযোগিতা।",
    ecommerceCons2: "আলাদা হতে উচ্চ বিপণন খরচ।",
    ecommerceCons3: "লজিস্টিকস এবং শিপিং জটিলতা।",
    ecommerceCons4: "গ্রাহকের বিশ্বাস এবং নিরাপত্তা উদ্বেগ।",
    ecommerceCons5: "ফেরত এবং গ্রাহক পরিষেবা ব্যবস্থাপনা।",

    technologyCons1: "দ্রুত প্রযুক্তিগত পরিবর্তন এবং অপ্রচলিততা।",
    technologyCons2: "উচ্চ গবেষণা ও উন্নয়ন খরচ এবং ক্রমাগত উদ্ভাবনের প্রয়োজন।",
    technologyCons3: "প্রতিভা অর্জন এবং ধরে রাখার চ্যালেঞ্জ।",
    technologyCons4: "মেধা সম্পত্তি সুরক্ষা।",
    technologyCons5: "বাজার গ্রহণ এবং স্কেলিং অসুবিধা।",

    healthcareCons1: "কঠোর নিয়মাবলী এবং সম্মতি প্রয়োজনীয়তা।",
    healthcareCons2: "সরঞ্জাম এবং সুবিধার জন্য উচ্চ মূলধন বিনিয়োগ।",
    healthcareCons3: "জটিল বিলিং এবং বীমা প্রক্রিয়া।",
    healthcareCons4: "কর্মী সংকট এবং উচ্চ শ্রম খরচ।",
    healthcareCons5: "অপচিকিৎসার মামলার ঝুঁকি।",

    fitnessCons1: "প্রতিষ্ঠিত জিম এবং অনলাইন প্ল্যাটফর্ম থেকে উচ্চ প্রতিযোগিতা।",
    fitnessCons2: "ক্লায়েন্ট ধরে রাখার চ্যালেঞ্জ।",
    fitnessCons3: "প্রত্যয়িত প্রশিক্ষক এবং মানসম্পন্ন সরঞ্জামের প্রয়োজন।",
    fitnessCons4: "মৌসুমী চাহিদার ওঠানামা।",
    fitnessCons5: "আঘাতের দায় এবং নিরাপত্তা উদ্বেগ।",

    // Help Center
    helpCenter: "সাহায্য কেন্দ্র",
    helpCenterDesc: "আপনার প্রশ্নের উত্তর খুঁজুন এবং গ্লোবালবিজ প্রো ব্যবহারের জন্য সহায়তা পান।",

    // Auth & Subscription
    login: "লগইন",
    signup: "সাইন আপ",
    logout: "লগআউট",
    username: "ব্যবহারকারীর নাম",
    password: "পাসওয়ার্ড",
    enterUsername: "আপনার ব্যবহারকারীর নাম লিখুন",
    enterPassword: "আপনার পাসওয়ার্ড লিখুন",
    loginSuccess: "সফলভাবে লগইন করা হয়েছে!",
    signupSuccess: "সফলভাবে সাইন আপ করা হয়েছে! আপনার ফ্রি ট্রায়াল উপভোগ করুন।",
    invalidCredentials: "অবৈধ ব্যবহারকারীর নাম বা পাসওয়ার্ড।",
    account: "অ্যাকাউন্ট",
    subscription: "সাবস্ক্রিপশন",
    subscriptionManager: "সাবস্ক্রিপশন ম্যানেজার",
    subscriptionManagerDesc: "আপনার সাবস্ক্রিপশন পরিচালনা করুন এবং ট্রায়াল স্থিতি দেখুন।",
    currentStatus: "বর্তমান অবস্থা",
    freeTrial: "ফ্রি ট্রায়াল",
    subscribed: "সাবস্ক্রাইব করা হয়েছে",
    trialDaysLeft: "দিন বাকি",
    trialUsesLeft: "ব্যবহার বাকি",
    trialExpired: "ট্রায়াল মেয়াদ উত্তীর্ণ",
    usesExhausted: "ব্যবহার শেষ",
    subscribeNow: "এখনই সাবস্ক্রাইব করুন",
    choosePlan: "আপনার প্ল্যান বেছে নিন",
    monthlyPlan: "মাসিক প্ল্যান",
    yearlyPlan: "বার্ষিক প্ল্যান",
    monthlyPrice: "৳9.99/মাস",
    yearlyPrice: "৳99.99/বছর (১৭% সাশ্রয় করুন)",
    selectPlan: "প্ল্যান নির্বাচন করুন",
    paymentMethod: "পেমেন্ট পদ্ধতি",
    selectPaymentMethod: "পেমেন্ট পদ্ধতি নির্বাচন করুন",
    bkash: "বিকাশ",
    creditCard: "ক্রেডিট কার্ড",
    paypal: "পেপ্যাল",
    payNow: "এখনই পেমেন্ট করুন",
    paymentProcessing: "পেমেন্ট প্রক্রিয়া করা হচ্ছে...",
    paymentSuccess: "পেমেন্ট সফল হয়েছে! আপনার সাবস্ক্রিপশন এখন সক্রিয়।",
    paymentFailed: "পেমেন্ট ব্যর্থ হয়েছে। অনুগ্রহ করে আবার চেষ্টা করুন।",
    premiumFeatureLocked: "এটি একটি প্রিমিয়াম বৈশিষ্ট্য। চালিয়ে যেতে অনুগ্রহ করে সাবস্ক্রাইব করুন বা আপনার ফ্রি ট্রায়াল শুরু করুন।",
    startFreeTrial: "ফ্রি ট্রায়াল শুরু করুন",
    trialLimitReached: "আপনার ফ্রি ট্রায়াল সীমা পৌঁছে গেছে। এই বৈশিষ্ট্যটি ব্যবহার চালিয়ে যেতে অনুগ্রহ করে সাবস্ক্রাইব করুন।",
    trialTimeExpired: "আপনার ফ্রি ট্রায়ালের মেয়াদ শেষ হয়ে গেছে। এই বৈশিষ্ট্যটি ব্যবহার চালিয়ে যেতে অনুগ্রহ করে সাবস্ক্রাইব করুন।",

    // Website Builder
    websiteBuilder: "ওয়েবসাইট বিল্ডার",
    websiteBuilderDesc: "আপনার ব্যবসার জন্য পেশাদার ওয়েবসাইট ডিজাইন এবং তৈরি করুন।",
    websiteName: "ওয়েবসাইটের নাম",
    websiteNamePlaceholder: "আপনার ওয়েবসাইটের নাম লিখুন",
    websiteTemplate: "ওয়েবসাইট টেমপ্লেট",
    selectTemplate: "টেমপ্লেট নির্বাচন করুন",
    templateModern: "আধুনিক ব্যবসা",
    templateCreative: "সৃজনশীল পোর্টফোলিও",
    templateEcommerce: "ই-কমার্স শপ",
    templateMinimal: "মিনিমালিস্ট ব্লগ",
    generateWebsite: "ওয়েবসাইট তৈরি করুন",
    generatedWebsite: "তৈরিকৃত ওয়েবসাইট",
    websitePreview: "ওয়েবসাইট পূর্বরূপ",
    downloadWebsite: "ওয়েবসাইট ডাউনলোড করুন (HTML/CSS)",
    websiteGenerating: "ওয়েবসাইট তৈরি হচ্ছে...",
    websiteGeneratedSuccess: "ওয়েবসাইট সফলভাবে তৈরি হয়েছে!",
    websiteGeneratedDesc: "আপনার কাস্টম-ডিজাইন করা ওয়েবসাইটের পূর্বরূপ দেখুন এবং ডাউনলোড করুন।",
  },
  hi: {
    tagline: "पूर्ण व्यावसायिक समाधान मंच",
    heroTitle: "AI-संचालित उपकरणों के साथ अपने सपनों का व्यवसाय बनाएं",
    heroSubtitle:
      "व्यावसायिक योजनाओं से लेकर लोगो तक, अपने व्यवसाय को दुनिया भर में शुरू करने और विकसित करने के लिए आवश्यक सब कुछ प्राप्त करें।",
    instantPlans: "AI व्यावसायिक योजनाएं",
    instantPlansDesc: "तत्काल व्यापक व्यावसायिक योजनाएं बनाएं",
    worldwideCosts: "वैश्विक लागत कैलकुलेटर",
    worldwideCostsDesc: "दुनिया भर के किसी भी देश के लिए लागत की गणना करें",
    designTools: "डिजाइन उपकरण",
    designToolsDesc: "पेशेवर रूप से लोगो और बैनर बनाएं",
    smartAnalysis: "स्मार्ट विश्लेषण",
    smartAnalysisDesc: "लाभ/हानि विश्लेषण और व्यावसायिक अंतर्दृष्टि",

    planGenerator: "योजना जेनरेटर",
    costCalculator: "लागत कैलकुलेटर",
    prosConsAnalysis: "लाभ/हानि",
    nameGenerator: "नाम जेनरेटर",
    logoDesign: "लोगो डिजाइन",
    bannerDesign: "बैनर डिजाइन",
    templates: "टेम्प्लेट",
    help: "सहायता",

    // Business Plan Generator
    aiBusinessPlanGenerator: "AI व्यावसायिक योजना जेनरेटर",
    aiGeneratorDesc: "विस्तृत लागत विश्लेषण और लाभ/हानि मूल्यांकन के साथ व्यापक व्यावसायिक योजनाएं बनाएं",
    businessName: "व्यवसाय का नाम",
    businessType: "व्यवसाय का प्रकार",
    location: "स्थान",
    initialBudget: "प्रारंभिक बजट",
    targetMarket: "लक्षित बाजार",
    experience: "आपका अनुभव",
    businessNamePlaceholder: "अपने व्यवसाय का नाम दर्ज करें",
    selectBusinessType: "व्यवसाय का प्रकार चुनें",
    locationPlaceholder: "अपना स्थान दर्ज करें",
    budgetPlaceholder: "अपना बजट दर्ज करें (जैसे: $50,000)",
    targetMarketPlaceholder: "अपने लक्षित ग्राहकों का वर्णन करें",
    experiencePlaceholder: "आपका प्रासंगिक अनुभव",
    generating: "तैयार की जा रही है...",
    generatePlan: "व्यावसायिक योजना बनाएं",
    generatedBusinessPlan: "तैयार की गई व्यावसायिक योजना",
    preview: "पूर्वावलोकन",
    downloadPDF: "PDF डाउनलोड करें",

    // Cost Calculator
    worldwideBusinessCostCalculator: "विश्वव्यापी व्यावसायिक लागत कैलकुलेटर",
    worldwideCostCalculatorDesc: "दुनिया भर के किसी भी देश और शहर के लिए विस्तृत व्यावसायिक लागत की गणना करें",
    country: "देश",
    city: "शहर",
    businessSize: "व्यवसाय का आकार",
    selectCountry: "देश चुनें",
    selectCity: "शहर चुनें",
    selectSize: "आकार चुनें",
    calculating: "गणना की जा रही है...",
    calculateCosts: "लागत की गणना करें",
    currency: "मुद्रा",
    locationInfo: "स्थान की जानकारी",

    // Business Types
    restaurant: "रेस्टोरेंट",
    retail: "खुदरा स्टोर",
    ecommerce: "ई-कॉमर्स",
    technology: "प्रौद्योगिकी",
    healthcare: "स्वास्थ्य सेवा",
    education: "शिक्षा",
    manufacturing: "विनिर्माण",
    service: "सेवा व्यवसाय",
    consulting: "परामर्श",
    agriculture: "कृषि",
    fitness: "फिटनेस और जिम",
    beauty: "सौंदर्य और सैलून",
    automotive: "ऑटोमोटिव",
    realestate: "रियल एस्टेट",
    travel: "यात्रा और पर्यटन",

    // Sizes
    small: "छोटा",
    medium: "मध्यम",
    large: "बड़ा",

    // Cost Categories
    oneTimeCosts: "एक बार की लागत",
    monthlyCosts: "मासिक लागत",
    yearlyCosts: "वार्षिक लागत",
    firstYearTotal: "पहले वर्ष का कुल",
    initialInvestment: "प्रारंभिक निवेश आवश्यक",
    recurringExpenses: "मासिक आवर्ती खर्च",
    annualOperating: "वार्षिक परिचालन लागत",
    totalInvestmentNeeded: "कुल निवेश आवश्यक",

    detailedCostBreakdown: "विस्तृत लागत विवरण",
    costBreakdownDesc: "सभी व्यावसायिक लागतों का पूर्ण विवरण",
    costCategory: "लागत श्रेणी",
    type: "प्रकार",
    amount: "राशि",
    oneTime: "एक बार",
    monthly: "मासिक",

    setupCosts: "सेटअप और पंजीकरण",
    equipmentCosts: "उपकरण और फर्नीचर",
    inventoryCosts: "प्रारंभिक इन्वेंटरी",
    licenseCosts: "लाइसेंस और परमिट",
    rentCosts: "किराया और उपयोगिताएं",
    salaryCosts: "कर्मचारी वेतन",
    staffCosts: "कर्मचारी वेतन",
    marketingCosts: "मार्केटिंग और विज्ञापन",
    utilityCosts: "उपयोगिताएं",
    insuranceCosts: "बीमा",
    otherCosts: "अन्य खर्च",

    // Business Plan Sections
    executiveSummary: "कार्यकारी सारांश",
    marketAnalysis: "बाजार विश्लेषण",
    productsServices: "उत्पाद और सेवाएं",
    marketingStrategy: "मार्केटिंग रणनीति",
    operationalPlan: "परिचालन योजना",
    managementTeam: "प्रबंधन टीम",
    financialProjections: "वित्तीय अनुमान",
    riskAnalysis: "जोखिम विश्लेषण",
    costBreakdown: "लागत विवरण",
    whyStartBusiness: "यह व्यवसाय क्यों शुरू करें",
    potentialChallenges: "संभावित चुनौतियां",
    estimatedCosts: "अनुमानित लागत",

    // Pros/Cons Analyzer
    prosConsAnalyzer: "व्यवसाय लाभ और हानि विश्लेषक",
    prosConsAnalyzerDesc: "अपने व्यावसायिक विचार के फायदे और चुनौतियों का विस्तृत विश्लेषण प्राप्त करें",
    selectLocation: "स्थान चुनें",
    analyzing: "विश्लेषण किया जा रहा है...",
    analyzeBusinessIdea: "व्यवसाय विचार का विश्लेषण करें",
    businessViabilityScore: "व्यवसाय व्यवहार्यता स्कोर",
    overallScore: "कुल स्कोर",
    difficulty: "कठिनाई",
    timeToProfit: "लाभ का समय",
    successRate: "सफलता दर",
    recommendations: "सिफारिशें",
    highlyRecommended: "अत्यधिक अनुशंसित",
    highlyRecommendedText: "यह व्यवसाय मजबूत बाजार मांग और अच्छे लाभ मार्जिन के साथ उत्कृष्ट क्षमता दिखाता है।",
    moderatelyRecommended: "मध्यम रूप से अनुशंसित",
    moderatelyRecommendedText: "इस व्यवसाय में क्षमता है लेकिन सावधानीपूर्वक योजना और निष्पादन की आवश्यकता है।",
    notRecommended: "सावधानी से आगे बढ़ें",
    notRecommendedText: "यह व्यवसाय महत्वपूर्ण चुनौतियों का सामना करता है। वैकल्पिक विकल्पों या व्यापक बाजार अनुसंधान पर विचार करें।",

    // Business Name Generator
    businessNameGenerator: "व्यवसाय नाम जेनरेटर",
    nameGeneratorDesc: "डोमेन उपलब्धता के साथ रचनात्मक और यादगार व्यावसायिक नाम बनाएं",
    keywords: "कीवर्ड",
    keywordsPlaceholder: "कीवर्ड दर्ज करें (जैसे: तेज, ताजा, तकनीक)",
    keywordsHint: "एकाधिक कीवर्ड को अल्पविराम से अलग करें",
    nameStyle: "नाम शैली",
    selectStyle: "शैली चुनें",
    generateNames: "नाम बनाएं",
    generatedNames: "तैयार किए गए नाम",
    generatedNamesDesc: "डोमेन उपलब्धता के साथ रचनात्मक व्यावसायिक नाम सुझाव",
    regenerate: "पुनः उत्पन्न करें",
    domain: "डोमेन",
    available: "उपलब्ध",
    taken: "लिया गया",
    rating: "रेटिंग",
    style: "शैली",

    // Name Styles
    modern: "आधुनिक",
    classic: "क्लासिक",
    creative: "रचनात्मक",
    professional: "पेशेवर",
    playful: "चंचल",
    luxury: "विलासिता",
    minimalist: "न्यूनतम",
    bold: "बोल्ड",
    elegant: "सुंदर",

    // Logo Designer
    logoDesigner: "AI लोगो डिजाइनर",
    logoDesignerDesc: "अपने व्यवसाय के लिए तुरंत पेशेवर लोगो बनाएं",
    industry: "उद्योग",
    selectIndustry: "उद्योग चुनें",
    logoStyle: "लोगो शैली",
    colorScheme: "रंग योजना",
    selectColor: "रंग चुनें",
    generateLogos: "लोगो बनाएं",
    generatedLogos: "तैयार किए गए लोगो",
    generatedLogosDesc: "आपके व्यवसाय के लिए पेशेवर लोगो डिजाइन",
    download: "डाउनलोड करें",

    // Colors
    blue: "नीला",
    green: "हरा",
    purple: "बैंगनी",
    red: "लाल",
    orange: "नारंगी",
    teal: "टील",
    pink: "गुलाबी",
    gray: "ग्रे",

    // Banner Designer
    bannerDesigner: "बैनर और पोस्टर डिजाइनर",
    bannerDesignerDesc: "विपणन के लिए शानदार बैनर और पोस्टर बनाएं",
    tagline: "टैगलाइन",
    taglinePlaceholder: "अपनी व्यावसायिक टैगलाइन दर्ज करें",
    bannerType: "बैनर प्रकार",
    selectBannerType: "बैनर प्रकार चुनें",
    bannerStyle: "बैनर शैली",
    generateBanners: "बैनर बनाएं",
    generatedBanners: "तैयार किए गए बैनर",
    generatedBannersDesc: "आपकी विपणन आवश्यकताओं के लिए कस्टम बैनर और पोस्टर",
    socialMedia: "सोशल मीडिया पोस्ट",
    websiteHeader: "वेबसाइट हेडर",
    facebookCover: "फेसबुक कवर",
    linkedinBanner: "लिंक्डइन बैनर",
    youtubeBanner: "यूट्यूब बैनर",
    instagramPost: "इंस्टाग्राम पोस्ट",

    // Templates
    businessTemplates: "व्यवसाय टेम्प्लेट",
    templatesDesc: "विभिन्न उद्योगों के लिए डिज़ाइन किए गए हमारे पूर्व-निर्मित टेम्प्लेट में से चुनें",
    difficulty: "कठिनाई",
    easy: "आसान",
    hard: "कठिन",
    investment: "निवेश",
    timeToStart: "शुरू करने का समय",
    profitMargin: "लाभ मार्जिन",
    generatePlan: "योजना बनाएं",
    calculateCosts: "लागत की गणना करें",

    // Template Descriptions
    restaurantDesc: "डाइन-इन, टेकआउट या डिलीवरी विकल्पों के साथ खाद्य सेवा व्यवसाय",
    retailDesc: "उपभोक्ताओं को उत्पाद बेचने वाला भौतिक या ऑनलाइन स्टोर",
    ecommerceDesc: "डिजिटल प्लेटफॉर्म के माध्यम से उत्पाद बेचने वाला ऑनलाइन व्यवसाय",
    technologyDesc: "सॉफ्टवेयर, ऐप डेवलपमेंट या टेक सर्विस व्यवसाय",
    healthcareDesc: "चिकित्सा सेवाएं, क्लिनिक या स्वास्थ्य संबंधी व्यवसाय",
    educationDesc: "स्कूल, प्रशिक्षण केंद्र या शैक्षिक सेवाएं",
    manufacturingDesc: "वस्तुओं का उत्पादन और विनिर्माण",
    serviceDesc: "सफाई, मरम्मत या परामर्श जैसे सेवा-आधारित व्यवसाय",
    consultingDesc: "आपकी विशेषज्ञता के क्षेत्र में पेशेवर सलाहकार सेवाएं",
    agricultureDesc: "खेती, पशुपालन या कृषि उत्पाद व्यवसाय",
    fitnessDesc: "जिम, व्यक्तिगत प्रशिक्षण, या वेलनेस सेंटर",
    beautyDesc: "सैलून, स्पा, या कॉस्मेटिक सेवाएं",
    automotiveDesc: "कार मरम्मत, बिक्री, या संबंधित सेवाएं",
    realestateDesc: "संपत्ति बिक्री, किराए, या विकास",
    travelDesc: "यात्रा एजेंसियां, टूर ऑपरेटर, या संबंधित सेवाएं",

    // Template Content
    executiveSummaryTemplate:
      "{location} में स्थित एक {businessType} व्यवसाय है, जो {targetMarket} को लक्षित करता है। {budget} के प्रारंभिक निवेश के साथ, हमारा लक्ष्य उच्च गुणवत्ता वाले उत्पाद/सेवाएं प्रदान करना और स्थानीय बाजार में टिकाऊ विकास प्राप्त करना है।",
    marketAnalysisTemplate:
      "{location} में {businessType} उद्योग मजबूत विकास की संभावना दिखाता है। हमारा लक्षित बाजार स्थानीय उपभोक्ताओं से मिलकर बना है जो गुणवत्ता और सुविधा को महत्व देते हैं। बाजार अनुसंधान हमारी सेवाओं की बढ़ती मांग का संकेत देता है।",
    productsServicesTemplate:
      "हमारा {businessType} हमारे लक्षित बाजार की विशिष्ट आवश्यकताओं को पूरा करने के लिए डिज़ाइन किए गए प्रीमियम उत्पाद/सेवाएं प्रदान करेगा। हम गुणवत्ता, ग्राहक संतुष्टि और प्रतिस्पर्धी मूल्य निर्धारण पर ध्यान केंद्रित करते हैं।",
    marketingStrategyTemplate:
      "हम डिजिटल मार्केटिंग, स्थानीय विज्ञापन और मुंह से मुंह रेफरल के माध्यम से {targetMarket} तक पहुंचेंगे। हमारा {businessType} ब्रांड जागरूकता बनाने के लिए सोशल मीडिया और सामुदायिक जुड़ाव का लाभ उठाएगा।",
    operationalPlanTemplate:
      "हमारा {businessType} कुशल प्रक्रियाओं और गुणवत्ता नियंत्रण उपायों के साथ {location} से संचालित होगा। हम सेवा वितरण और ग्राहक संतुष्टि के उच्च मानकों को बनाए रखेंगे।",
    managementTeamTemplate:
      "प्रबंधन टीम व्यवसाय में {experience} लाती है, दीर्घकालिक सफलता के लिए पेशेवर संचालन और रणनीतिक निर्णय लेने को सुनिश्चित करती है।",
    financialProjectionsTemplate:
      "{budget} के प्रारंभिक निवेश के साथ, हमारा {businessType} स्थिर राजस्व वृद्धि और संचालन के पहले वर्ष के भीतर लाभप्रदता का अनुमान लगाता है।",
    riskAnalysisTemplate:
      "हमारे {businessType} के लिए मुख्य जोखिमों में बाजार प्रतिस्पर्धा, आर्थिक उतार-चढ़ाव और परिचालन चुनौतियां शामिल हैं। हमने इन संभावित मुद्दों से निपटने के लिए शमन रणनीतियां विकसित की हैं।",

    // Pros for Business Types
    restaurantPros1: "भोजन और भोजन के अनुभवों के लिए उच्च मांग।",
    restaurantPros2: "मेनू और माहौल में रचनात्मकता का अवसर।",
    restaurantPros3: "मजबूत सामुदायिक जुड़ाव की संभावना।",
    restaurantPros4: "विविध राजस्व धाराएं (डाइन-इन, टेकआउट, कैटरिंग)।",
    restaurantPros5: "कई स्थानों या फ्रेंचाइज़िंग के माध्यम से स्केलेबिलिटी।",

    retailPros1: "सीधा ग्राहक संपर्क और प्रतिक्रिया।",
    retailPros2: "भौतिक उत्पादों को प्रदर्शित करने की क्षमता।",
    retailPros3: "एक स्थानीय ब्रांड उपस्थिति का निर्माण।",
    retailPros4: "व्यक्तिगत ग्राहक सेवा का अवसर।",
    retailPros5: "स्थानीय बाजार के रुझानों के लिए तेजी से अनुकूलन।",

    ecommercePros1: "भौतिक दुकानों की तुलना में कम ओवरहेड लागत।",
    ecommercePros2: "वैश्विक पहुंच और 24/7 बिक्री की क्षमता।",
    ecommercePros3: "कम भौतिक बुनियादी ढांचे के साथ स्केलेबिलिटी।",
    ecommercePros4: "डेटा-संचालित विपणन और वैयक्तिकरण।",
    ecommercePros5: "उत्पाद पेशकश और इन्वेंट्री प्रबंधन में लचीलापन।",

    technologyPros1: "सफल उत्पादों/सेवाओं के लिए उच्च लाभ मार्जिन।",
    technologyPros2: "तेजी से नवाचार और विकास की क्षमता।",
    technologyPros3: "एक बड़े उपयोगकर्ता आधार को प्रभावित करने की क्षमता।",
    technologyPros4: "अत्यधिक कुशल प्रतिभा को आकर्षित करता है।",
    technologyPros5: "महत्वपूर्ण निवेश और अधिग्रहण की क्षमता।",

    healthcarePros1: "स्वास्थ्य सेवाओं के लिए हमेशा मौजूद मांग।",
    healthcarePros2: "उच्च विश्वास और प्रतिष्ठा निर्माण की क्षमता।",
    healthcarePros3: "सकारात्मक सामाजिक प्रभाव।",
    healthcarePros4: "आवर्ती सेवाओं से स्थिर राजस्व धाराएं।",
    healthcarePros5: "विशेषज्ञता और विशिष्ट बाजारों के लिए अवसर।",

    fitnessPros1: "बढ़ता स्वास्थ्य और कल्याण का रुझान।",
    fitnessPros2: "सामुदायिक निर्माण और वफादार ग्राहक आधार।",
    fitnessPros3: "विविध सेवा पेशकश (कक्षाएं, व्यक्तिगत प्रशिक्षण)।",
    fitnessPros4: "ग्राहकों के जीवन पर सकारात्मक प्रभाव।",
    fitnessPros5: "कुछ मॉडलों के लिए अपेक्षाकृत कम स्टार्टअप लागत (जैसे, ऑनलाइन कोचिंग)।",

    // Cons for Business Types
    restaurantCons1: "उच्च स्टार्टअप और परिचालन लागत।",
    restaurantCons2: "तीव्र प्रतिस्पर्धा और उच्च विफलता दर।",
    restaurantCons3: "लंबे काम के घंटे और मांग वाला कार्यक्रम।",
    restaurantCons4: "कर्मचारियों और भोजन की गुणवत्ता की निरंतरता पर निर्भरता।",
    restaurantCons5: "नियामक अनुपालन और स्वास्थ्य निरीक्षण।",

    retailCons1: "उच्च ओवरहेड (किराया, उपयोगिताएं, इन्वेंट्री)।",
    retailCons2: "ई-कॉमर्स और बड़ी श्रृंखलाओं से प्रतिस्पर्धा।",
    retailCons3: "इन्वेंट्री प्रबंधन चुनौतियां।",
    retailCons4: "बिक्री में मौसमी उतार-चढ़ाव।",
    retailCons5: "मजबूत दृश्य मर्चेंडाइजिंग और ग्राहक अनुभव की आवश्यकता।",

    ecommerceCons1: "तीव्र ऑनलाइन प्रतिस्पर्धा।",
    ecommerceCons2: "अलग दिखने के लिए उच्च विपणन लागत।",
    ecommerceCons3: "लॉजिस्टिक्स और शिपिंग जटिलताएं।",
    ecommerceCons4: "ग्राहक विश्वास और सुरक्षा चिंताएं।",
    ecommerceCons5: "रिटर्न और ग्राहक सेवा प्रबंधन।",

    technologyCons1: "तेजी से तकनीकी परिवर्तन और अप्रचलन।",
    technologyCons2: "उच्च आर एंड डी लागत और निरंतर नवाचार की आवश्यकता।",
    technologyCons3: "प्रतिभा अधिग्रहण और प्रतिधारण चुनौतियां।",
    technologyCons4: "बौद्धिक संपदा संरक्षण।",
    technologyCons5: "बाजार अपनाने और स्केलिंग कठिनाइयां।",

    healthcareCons1: "कठोर नियम और अनुपालन आवश्यकताएं।",
    healthcareCons2: "उपकरण और सुविधाओं के लिए उच्च पूंजी निवेश।",
    healthcareCons3: "जटिल बिलिंग और बीमा प्रक्रियाएं।",
    healthcareCons4: "कर्मचारियों की कमी और उच्च श्रम लागत।",
    healthcareCons5: "कुप्रथा मुकदमों का जोखिम।",

    fitnessCons1: "स्थापित जिम और ऑनलाइन प्लेटफॉर्म से उच्च प्रतिस्पर्धा।",
    fitnessCons2: "ग्राहक प्रतिधारण चुनौतियां।",
    fitnessCons3: "प्रमाणित प्रशिक्षकों और गुणवत्ता वाले उपकरणों की आवश्यकता।",
    fitnessCons4: "मौसमी मांग में उतार-चढ़ाव।",
    fitnessCons5: "चोट की देयता और सुरक्षा चिंताएं।",

    // Help Center
    helpCenter: "सहायता केंद्र",
    helpCenterDesc: "अपने प्रश्नों के उत्तर खोजें और ग्लोबलबिज प्रो का उपयोग करने के लिए सहायता प्राप्त करें।",

    // Auth & Subscription
    login: "लॉगिन",
    signup: "साइन अप करें",
    logout: "लॉगआउट",
    username: "उपयोगकर्ता नाम",
    password: "पासवर्ड",
    enterUsername: "अपना उपयोगकर्ता नाम दर्ज करें",
    enterPassword: "अपना पासवर्ड दर्ज करें",
    loginSuccess: "सफलतापूर्वक लॉग इन किया गया!",
    signupSuccess: "सफलतापूर्वक साइन अप किया गया! अपने निःशुल्क परीक्षण का आनंद लें।",
    invalidCredentials: "अमान्य उपयोगकर्ता नाम या पासवर्ड।",
    account: "खाता",
    subscription: "सदस्यता",
    subscriptionManager: "सदस्यता प्रबंधक",
    subscriptionManagerDesc: "अपनी सदस्यता प्रबंधित करें और परीक्षण स्थिति देखें।",
    currentStatus: "वर्तमान स्थिति",
    freeTrial: "निःशुल्क परीक्षण",
    subscribed: "सदस्यता ली गई",
    trialDaysLeft: "दिन शेष",
    trialUsesLeft: "उपयोग शेष",
    trialExpired: "परीक्षण समाप्त",
    usesExhausted: "उपयोग समाप्त",
    subscribeNow: "अभी सदस्यता लें",
    choosePlan: "अपनी योजना चुनें",
    monthlyPlan: "मासिक योजना",
    yearlyPlan: "वार्षिक योजना",
    monthlyPrice: "$9.99/माह",
    yearlyPrice: "$99.99/वर्ष (17% बचाएं)",
    selectPlan: "योजना चुनें",
    paymentMethod: "भुगतान विधि",
    selectPaymentMethod: "भुगतान विधि चुनें",
    bkash: "बिकाश",
    creditCard: "क्रेडिट कार्ड",
    paypal: "पेपैल",
    payNow: "अभी भुगतान करें",
    paymentProcessing: "भुगतान संसाधित हो रहा है...",
    paymentSuccess: "भुगतान सफल! आपकी सदस्यता अब सक्रिय है।",
    paymentFailed: "भुगतान विफल। कृपया पुनः प्रयास करें।",
    premiumFeatureLocked: "यह एक प्रीमियम सुविधा है। जारी रखने के लिए कृपया सदस्यता लें या अपना निःशुल्क परीक्षण शुरू करें।",
    startFreeTrial: "निःशुल्क परीक्षण शुरू करें",
    trialLimitReached: "आपकी निःशुल्क परीक्षण सीमा पूरी हो गई है। इस सुविधा का उपयोग जारी रखने के लिए कृपया सदस्यता लें।",
    trialTimeExpired: "आपका निःशुल्क परीक्षण समाप्त हो गया है। इस सुविधा का उपयोग जारी रखने के लिए कृपया सदस्यता लें।",

    // Website Builder
    websiteBuilder: "वेबसाइट बिल्डर",
    websiteBuilderDesc: "अपने व्यवसाय के लिए पेशेवर वेबसाइट डिज़ाइन और बनाएं।",
    websiteName: "वेबसाइट का नाम",
    websiteNamePlaceholder: "अपनी वेबसाइट का नाम दर्ज करें",
    websiteTemplate: "वेबसाइट टेम्पलेट",
    selectTemplate: "टेम्पलेट चुनें",
    templateModern: "आधुनिक व्यवसाय",
    templateCreative: "रचनात्मक पोर्टफोलियो",
    templateEcommerce: "ई-कॉमर्स शॉप",
    templateMinimal: "न्यूनतम ब्लॉग",
    generateWebsite: "वेबसाइट बनाएं",
    generatedWebsite: "तैयार की गई वेबसाइट",
    websitePreview: "वेबसाइट पूर्वावलोकन",
    downloadWebsite: "वेबसाइट डाउनलोड करें (HTML/CSS)",
    websiteGenerating: "वेबसाइट बनाई जा रही है...",
    websiteGeneratedSuccess: "वेबसाइट सफलतापूर्वक बनाई गई!",
    websiteGeneratedDesc: "अपनी कस्टम-डिज़ाइन की गई वेबसाइट का पूर्वावलोकन करें और डाउनलोड करें।",
  },
  es: {
    tagline: "Plataforma Completa de Soluciones Empresariales",
    heroTitle: "Construye el Negocio de tus Sueños con Herramientas Impulsadas por IA",
    heroSubtitle:
      "Desde planes de negocio hasta logotipos, obtén todo lo que necesitas para iniciar y hacer crecer tu negocio en todo el mundo.",
    instantPlans: "Planes de Negocio con IA",
    instantPlansDesc: "Genera planes de negocio completos al instante",
    worldwideCosts: "Calculadora de Costos Global",
    worldwideCostsDesc: "Calcula costos para cualquier país del mundo",
    designTools: "Herramientas de Diseño",
    designToolsDesc: "Crea logotipos y banners profesionalmente",
    smartAnalysis: "Análisis Inteligente",
    smartAnalysisDesc: "Análisis de pros y contras e información empresarial",

    planGenerator: "Generador de Planes",
    costCalculator: "Calculadora de Costos",
    prosConsAnalysis: "Pros/Contras",
    nameGenerator: "Generador de Nombres",
    logoDesign: "Diseño de Logotipos",
    bannerDesign: "Diseño de Banners",
    templates: "Plantillas",
    help: "Ayuda",

    // Business Plan Generator
    aiBusinessPlanGenerator: "Generador de Plan de Negocio con IA",
    aiGeneratorDesc:
      "Crea planes de negocio completos con análisis detallados de costos y evaluación de pros y contras",
    businessName: "Nombre del Negocio",
    businessType: "Tipo de Negocio",
    location: "Ubicación",
    initialBudget: "Presupuesto Inicial",
    targetMarket: "Mercado Objetivo",
    experience: "Tu Experiencia",
    businessNamePlaceholder: "Ingresa el nombre de tu negocio",
    selectBusinessType: "Selecciona el tipo de negocio",
    locationPlaceholder: "Ingresa tu ubicación",
    budgetPlaceholder: "Ingresa tu presupuesto (ej: $50,000)",
    targetMarketPlaceholder: "Describe tus clientes objetivo",
    experiencePlaceholder: "Tu experiencia relevante",
    generating: "Generando...",
    generatePlan: "Generar Plan de Negocio",
    generatedBusinessPlan: "Plan de Negocio Generado",
    preview: "Vista Previa",
    downloadPDF: "Descargar PDF",

    // Cost Calculator
    worldwideBusinessCostCalculator: "Calculadora de Costos Empresariales Mundial",
    worldwideCostCalculatorDesc: "Calcula costos empresariales detallados para cualquier país y ciudad del mundo",
    country: "País",
    city: "Ciudad",
    businessSize: "Tamaño del Negocio",
    selectCountry: "Seleccionar país",
    selectCity: "Seleccionar ciudad",
    selectSize: "Seleccionar tamaño",
    calculating: "Calculando...",
    calculateCosts: "Calcular Costos",
    currency: "Moneda",
    locationInfo: "Información de Ubicación",

    // Business Types
    restaurant: "Restaurante",
    retail: "Tienda Minorista",
    ecommerce: "E-commerce",
    technology: "Tecnología",
    healthcare: "Salud",
    education: "Educación",
    manufacturing: "Manufactura",
    service: "Negocio de Servicios",
    consulting: "Consultoría",
    agriculture: "Agricultura",
    fitness: "Fitness y Gimnasio",
    beauty: "Belleza y Salón",
    automotive: "Automotriz",
    realestate: "Bienes Raíces",
    travel: "Viajes y Turismo",

    // Sizes
    small: "Pequeño",
    medium: "Mediano",
    large: "Grande",

    // Cost Categories
    oneTimeCosts: "Costos Únicos",
    monthlyCosts: "Costos Mensuales",
    yearlyCosts: "Costos Anuales",
    firstYearTotal: "Total Primer Año",
    initialInvestment: "Inversión inicial requerida",
    recurringExpenses: "Gastos recurrentes mensuales",
    annualOperating: "Costos operativos anuales",
    totalInvestmentNeeded: "Inversión total necesaria",

    detailedCostBreakdown: "Desglose Detallado de Costos",
    costBreakdownDesc: "Desglose completo de todos los costos empresariales",
    costCategory: "Categoría de Costo",
    type: "Tipo",
    amount: "Cantidad",
    oneTime: "Una vez",
    monthly: "Mensual",

    setupCosts: "Configuración y Registro",
    equipmentCosts: "Equipos y Mobiliario",
    inventoryCosts: "Inventario Inicial",
    licenseCosts: "Licencias y Permisos",
    rentCosts: "Alquiler y Servicios",
    salaryCosts: "Salarios del Personal",
    staffCosts: "Salarios del Personal",
    marketingCosts: "Marketing y Publicidad",
    utilityCosts: "Servicios Públicos",
    insuranceCosts: "Seguros",
    otherCosts: "Otros Gastos",

    // Business Plan Sections
    executiveSummary: "Resumen Ejecutivo",
    marketAnalysis: "Análisis de Mercado",
    productsServices: "Productos y Servicios",
    marketingStrategy: "Estrategia de Marketing",
    operationalPlan: "Plan Operacional",
    managementTeam: "Equipo de Gestión",
    financialProjections: "Proyecciones Financieras",
    riskAnalysis: "Análisis de Riesgos",
    costBreakdown: "Desglose de Costos",
    whyStartBusiness: "Por Qué Iniciar Este Negocio",
    potentialChallenges: "Desafíos Potenciales",
    estimatedCosts: "Costos Estimados",

    // Pros/Cons Analyzer
    prosConsAnalyzer: "Analizador de Pros y Contras del Negocio",
    prosConsAnalyzerDesc: "Obtén un análisis detallado de las ventajas y desafíos para tu idea de negocio",
    selectLocation: "Seleccionar ubicación",
    analyzing: "Analizando...",
    analyzeBusinessIdea: "Analizar Idea de Negocio",
    businessViabilityScore: "Puntuación de Viabilidad del Negocio",
    overallScore: "Puntuación General",
    difficulty: "Dificultad",
    timeToProfit: "Tiempo para Obtener Ganancias",
    successRate: "Tasa de Éxito",
    recommendations: "Recomendaciones",
    highlyRecommended: "Altamente Recomendado",
    highlyRecommendedText:
      "Este negocio muestra un excelente potencial con una fuerte demanda del mercado y buenos márgenes de beneficio.",
    moderatelyRecommended: "Moderadamente Recomendado",
    moderatelyRecommendedText: "Este negocio tiene potencial pero requiere una planificación y ejecución cuidadosas.",
    notRecommended: "Proceder con Precaución",
    notRecommendedText:
      "Este negocio enfrenta desafíos significativos. Considera opciones alternativas o una investigación de mercado exhaustiva.",

    // Business Name Generator
    businessNameGenerator: "Generador de Nombres de Negocio",
    nameGeneratorDesc: "Genera nombres de negocio creativos y memorables con disponibilidad de dominio",
    keywords: "Palabras Clave",
    keywordsPlaceholder: "Ingresa palabras clave (ej: rápido, fresco, tecnología)",
    keywordsHint: "Separa múltiples palabras clave con comas",
    nameStyle: "Estilo de Nombre",
    selectStyle: "Seleccionar estilo",
    generateNames: "Generar Nombres",
    generatedNames: "Nombres Generados",
    generatedNamesDesc: "Sugerencias de nombres de negocio creativos con disponibilidad de dominio",
    regenerate: "Regenerar",
    domain: "Dominio",
    available: "Disponible",
    taken: "Ocupado",
    rating: "Calificación",
    style: "Estilo",

    // Name Styles
    modern: "Moderno",
    classic: "Clásico",
    creative: "Creativo",
    professional: "Profesional",
    playful: "Juguetón",
    luxury: "Lujo",
    minimalist: "Minimalista",
    bold: "Audaz",
    elegant: "Elegante",

    // Logo Designer
    logoDesigner: "Diseñador de Logotipos con IA",
    logoDesignerDesc: "Crea logotipos profesionales para tu negocio al instante",
    industry: "Industria",
    selectIndustry: "Seleccionar industria",
    logoStyle: "Estilo de Logotipo",
    colorScheme: "Esquema de Colores",
    selectColor: "Seleccionar color",
    generateLogos: "Generar Logotipos",
    generatedLogos: "Logotipos Generados",
    generatedLogosDesc: "Diseños de logotipos profesionales para tu negocio",
    download: "Descargar",

    // Colors
    blue: "Azul",
    green: "Verde",
    purple: "Morado",
    red: "Rojo",
    orange: "Naranja",
    teal: "Verde Azulado",
    pink: "Rosa",
    gray: "Gris",

    // Banner Designer
    bannerDesigner: "Diseñador de Banners y Pósters",
    bannerDesignerDesc: "Crea banners y pósters impresionantes para marketing",
    tagline: "Eslogan",
    taglinePlaceholder: "Ingresa el eslogan de tu negocio",
    bannerType: "Tipo de Banner",
    selectBannerType: "Seleccionar tipo de banner",
    bannerStyle: "Estilo de Banner",
    generateBanners: "Generar Banners",
    generatedBanners: "Banners Generados",
    generatedBannersDesc: "Banners y pósters personalizados para tus necesidades de marketing",
    socialMedia: "Publicación en Redes Sociales",
    websiteHeader: "Encabezado de Sitio Web",
    facebookCover: "Portada de Facebook",
    linkedinBanner: "Banner de LinkedIn",
    youtubeBanner: "Banner de YouTube",
    instagramPost: "Publicación de Instagram",

    // Templates
    businessTemplates: "Plantillas de Negocio",
    templatesDesc: "Elige entre nuestras plantillas prediseñadas para diferentes industrias",
    difficulty: "Dificultad",
    easy: "Fácil",
    hard: "Difícil",
    investment: "Inversión",
    timeToStart: "Tiempo para Iniciar",
    profitMargin: "Margen de Ganancia",
    generatePlan: "Generar Plan",
    calculateCosts: "Calcular Costos",

    // Template Descriptions
    restaurantDesc: "Negocio de servicio de comida con opciones de comer en el lugar, para llevar o entrega",
    retailDesc: "Tienda física u online que vende productos a consumidores",
    ecommerceDesc: "Negocio online que vende productos a través de plataformas digitales",
    technologyDesc: "Software, desarrollo de apps o negocio de servicios tecnológicos",
    healthcareDesc: "Servicios médicos, clínicas o negocios relacionados con la salud",
    educationDesc: "Escuelas, centros de entrenamiento o servicios educativos",
    manufacturingDesc: "Producción y manufactura de bienes",
    serviceDesc: "Negocio basado en servicios como limpieza, reparación o consultoría",
    consultingDesc: "Servicios de asesoría profesional en tu área de experiencia",
    agricultureDesc: "Agricultura, ganadería o negocio de productos agrícolas",
    fitnessDesc: "Gimnasios, entrenamiento personal o centros de bienestar",
    beautyDesc: "Salones, spas o servicios cosméticos",
    automotiveDesc: "Reparación de automóviles, ventas o servicios relacionados",
    realestateDesc: "Venta de propiedades, alquileres o desarrollo",
    travelDesc: "Agencias de viajes, operadores turísticos o servicios relacionados",

    // Template Content
    executiveSummaryTemplate:
      "es un negocio de {businessType} ubicado en {location}, dirigido a {targetMarket}. Con una inversión inicial de {budget}, nuestro objetivo es proporcionar productos/servicios de alta calidad y lograr un crecimiento sostenible en el mercado local.",
    marketAnalysisTemplate:
      "La industria de {businessType} en {location} muestra un fuerte potencial de crecimiento. Nuestro mercado objetivo consiste en consumidores locales que valoran la calidad y la conveniencia. La investigación de mercado indica una demanda creciente para nuestros servicios.",
    productsServicesTemplate:
      "Nuestro {businessType} ofrecerá productos/servicios premium diseñados para satisfacer las necesidades específicas de nuestro mercado objetivo. Nos enfocamos en la calidad, satisfacción del cliente y precios competitivos.",
    marketingStrategyTemplate:
      "Llegaremos a {targetMarket} a través de marketing digital, publicidad local y referencias de boca en boca. Nuestro {businessType} aprovechará las redes sociales y el compromiso comunitario para construir conciencia de marca.",
    operationalPlanTemplate:
      "Nuestro {businessType} operará desde {location} con procesos eficientes y medidas de control de calidad. Mantendremos altos estándares de entrega de servicios y satisfacción del cliente.",
    managementTeamTemplate:
      "El equipo de gestión aporta {experience} al negocio, asegurando operaciones profesionales y toma de decisiones estratégicas para el éxito a largo plazo.",
    financialProjectionsTemplate:
      "Con una inversión inicial de {budget}, nuestro {businessType} proyecta un crecimiento constante de ingresos y rentabilidad dentro del primer año de operaciones.",
    riskAnalysisTemplate:
      "Los riesgos clave para nuestro {businessType} incluyen competencia de mercado, fluctuaciones económicas y desafíos operacionales. Hemos desarrollado estrategias de mitigación para abordar estos problemas potenciales.",

    // Pros for Business Types
    restaurantPros1: "Alta demanda de experiencias gastronómicas y culinarias.",
    restaurantPros2: "Oportunidad de creatividad en el menú y el ambiente.",
    restaurantPros3: "Fuerte potencial de participación comunitaria.",
    restaurantPros4: "Diversas fuentes de ingresos (comer en el lugar, para llevar, catering).",
    restaurantPros5: "Escalabilidad a través de múltiples ubicaciones o franquicias.",

    retailPros1: "Interacción directa con el cliente y retroalimentación.",
    retailPros2: "Capacidad para exhibir productos físicos.",
    retailPros3: "Construcción de una presencia de marca local.",
    retailPros4: "Oportunidad de servicio al cliente personalizado.",
    retailPros5: "Adaptación rápida a las tendencias del mercado local.",

    ecommercePros1: "Costos generales bajos en comparación con las tiendas físicas.",
    ecommercePros2: "Alcance global y potencial de ventas 24/7.",
    ecommercePros3: "Escalabilidad con menos infraestructura física.",
    ecommercePros4: "Marketing basado en datos y personalización.",
    ecommercePros5: "Flexibilidad en la oferta de productos y gestión de inventario.",

    technologyPros1: "Altos márgenes de beneficio para productos/servicios exitosos.",
    technologyPros2: "Rápida innovación y potencial de crecimiento.",
    technologyPros3: "Capacidad para impactar una gran base de usuarios.",
    technologyPros4: "Atrae talento altamente calificado.",
    technologyPros5: "Potencial de inversión y adquisición significativas.",

    healthcarePros1: "Demanda siempre presente de servicios de salud.",
    healthcarePros2: "Alto potencial de construcción de confianza y reputación.",
    healthcarePros3: "Impacto social positivo.",
    healthcarePros4: "Fuentes de ingresos estables de servicios recurrentes.",
    healthcarePros5: "Oportunidades de especialización y nichos de mercado.",

    fitnessPros1: "Tendencia creciente de salud y bienestar.",
    fitnessPros2: "Construcción de comunidad y base de clientes leales.",
    fitnessPros3: "Diversas ofertas de servicios (clases, entrenamiento personal).",
    fitnessPros4: "Impacto positivo en la vida de los clientes.",
    fitnessPros5: "Costos de inicio relativamente bajos para ciertos modelos (ej., entrenamiento en línea).",

    // Cons for Business Types
    restaurantCons1: "Altos costos de inicio y operación.",
    restaurantCons2: "Intensa competencia y alta tasa de fracaso.",
    restaurantCons3: "Horas de trabajo largas y horario exigente.",
    restaurantCons4: "Dependencia del personal y la consistencia de la calidad de los alimentos.",
    restaurantCons5: "Cumplimiento normativo e inspecciones de salud.",

    retailCons1: "Altos costos generales (alquiler, servicios públicos, inventario).",
    retailCons2: "Competencia del comercio electrónico y grandes cadenas.",
    retailCons3: "Desafíos de gestión de inventario.",
    retailCons4: "Fluctuaciones estacionales en las ventas.",
    retailCons5: "Necesidad de un fuerte merchandising visual y experiencia del cliente.",

    ecommerceCons1: "Intensa competencia en línea.",
    ecommerceCons2: "Altos costos de marketing para destacar.",
    ecommerceCons3: "Complejidades de logística y envío.",
    ecommerceCons4: "Preocupaciones de confianza y seguridad del cliente.",
    ecommerceCons5: "Gestión de devoluciones y servicio al cliente.",

    technologyCons1: "Rápidos cambios tecnológicos y obsolescencia.",
    technologyCons2: "Altos costos de I+D y necesidad de innovación continua.",
    technologyCons3: "Desafíos de adquisición y retención de talento.",
    technologyCons4: "Protección de la propiedad intelectual.",
    technologyCons5: "Dificultades de adopción y escalado del mercado.",

    healthcareCons1: "Estrictas regulaciones y requisitos de cumplimiento.",
    healthcareCons2: "Alta inversión de capital para equipos e instalaciones.",
    healthcareCons3: "Procesos complejos de facturación y seguros.",
    healthcareCons4: "Escasez de personal y altos costos laborales.",
    healthcareCons5: "Riesgo de demandas por negligencia.",

    fitnessCons1: "Alta competencia de gimnasios establecidos y plataformas en línea.",
    fitnessCons2: "Desafíos de retención de clientes.",
    fitnessCons3: "Necesidad de entrenadores certificados y equipos de calidad.",
    fitnessCons4: "Fluctuaciones estacionales de la demanda.",
    fitnessCons5: "Responsabilidad por lesiones y preocupaciones de seguridad.",

    // Help Center
    helpCenter: "Centro de Ayuda",
    helpCenterDesc: "Encuentra respuestas a tus preguntas y obtén soporte para usar GlobalBiz Pro.",

    // Auth & Subscription
    login: "Iniciar Sesión",
    signup: "Registrarse",
    logout: "Cerrar Sesión",
    username: "Nombre de Usuario",
    password: "Contraseña",
    enterUsername: "Ingresa tu nombre de usuario",
    enterPassword: "Ingresa tu contraseña",
    loginSuccess: "¡Sesión iniciada con éxito!",
    signupSuccess: "¡Registrado con éxito! Disfruta de tu prueba gratuita.",
    invalidCredentials: "Credenciales inválidas.",
    account: "Cuenta",
    subscription: "Suscripción",
    subscriptionManager: "Administrador de Suscripciones",
    subscriptionManagerDesc: "Gestiona tu suscripción y ve el estado de tu prueba.",
    currentStatus: "Estado Actual",
    freeTrial: "Prueba Gratuita",
    subscribed: "Suscrito",
    trialDaysLeft: "Días Restantes",
    trialUsesLeft: "Usos Restantes",
    trialExpired: "Prueba Expirada",
    usesExhausted: "Usos Agotados",
    subscribeNow: "Suscribirse Ahora",
    choosePlan: "Elige Tu Plan",
    monthlyPlan: "Plan Mensual",
    yearlyPlan: "Plan Anual",
    monthlyPrice: "$9.99/mes",
    yearlyPrice: "$99.99/año (Ahorra 17%)",
    selectPlan: "Seleccionar Plan",
    paymentMethod: "Método de Pago",
    selectPaymentMethod: "Seleccionar Método de Pago",
    bkash: "Bkash",
    creditCard: "Tarjeta de Crédito",
    paypal: "PayPal",
    payNow: "Pagar Ahora",
    paymentProcessing: "Procesando Pago...",
    paymentSuccess: "¡Pago exitoso! Tu suscripción está activa.",
    paymentFailed: "El pago falló. Por favor, inténtalo de nuevo.",
    premiumFeatureLocked:
      "Esta es una característica premium. Por favor, suscríbete o inicia tu prueba gratuita para continuar.",
    startFreeTrial: "Iniciar Prueba Gratuita",
    trialLimitReached:
      "Tu límite de prueba gratuita ha sido alcanzado. Por favor, suscríbete para seguir usando esta función.",
    trialTimeExpired: "Tu prueba gratuita ha expirado. Por favor, suscríbete para seguir usando esta función.",

    // Website Builder
    websiteBuilder: "Constructor de Sitios Web",
    websiteBuilderDesc: "Diseña y genera sitios web profesionales para tu negocio.",
    websiteName: "Nombre del Sitio Web",
    websiteNamePlaceholder: "Ingresa el nombre de tu sitio web",
    websiteTemplate: "Plantilla de Sitio Web",
    selectTemplate: "Seleccionar plantilla",
    templateModern: "Negocio Moderno",
    templateCreative: "Portafolio Creativo",
    templateEcommerce: "Tienda de E-commerce",
    templateMinimal: "Blog Minimalista",
    generateWebsite: "Generar Sitio Web",
    generatedWebsite: "Sitio Web Generado",
    websitePreview: "Vista Previa del Sitio Web",
    downloadWebsite: "Descargar Sitio Web (HTML/CSS)",
    websiteGenerating: "Generando Sitio Web...",
    websiteGeneratedSuccess: "¡Sitio web generado con éxito!",
    websiteGeneratedDesc: "Previsualiza y descarga tu sitio web diseñado a medida.",
  },
}

const languages = {
  en: "English",
  bn: "বাংলা",
  hi: "हिन्दी",
  es: "Español",
}

export function useLanguage() {
  const [language, setLanguage] = useState("bn")

  const t = translations[language as keyof typeof translations] || translations.en

  return {
    language,
    setLanguage,
    t,
    languages,
  }
}
